[package]
name = "advanced-algo-and-struct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "advanced"
path = "src/lib.rs"
